### ISSUE TITLE
Codes not written in OpenGL

### ISSUE THREAD

**Issue by andymiller813** [mwalczyk/flow#1]
I have one issue with this codes and that is I do not understand why you choose to write in Vulkan and not the superior OpenGL.  Please respond thx

**Comment by mwalczyk** [comment]
Greetings @andymiller813 ! Great to see you checking out my project. The reason why we do not use OpenGL is because it does not support the underscoreunderscoreGLOBALunderscoreunderscore attribute. Thanks!

**Comment by andymiller813** [comment]
Ahhh but of course!!!1!11
